spring:
  application:
    name: dorm
  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/dorm_management?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8080
  servlet:
    session:
      timeout: 30m  # Session超时时间30分钟
      cookie:
        name: DORM_SESSION
        http-only: true
        secure: false  # 开发环境设为false，生产环境建议true

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名映射开关
    map-underscore-to-camel-case: false